### ISSUE TITLE
AttributeError: 'DatetimeIndex' object has no attribute 'isocalendar'

### ISSUE THREAD

**Issue by xiaozhezju** [tomkwok/calplot#18]
When I ran the sample code
`all_days = pd.date_range('1/1/2019', periods=730, freq='D')
days = np.random.choice(all_days, 500)
events = pd.Series(np.random.randn(len(days)), index=days)
calplot.calplot(events, cmap='YlGn', colorbar=False)`

Python raised an error about pandas, can anyone know why?

**Comment by xiaozhezju** [comment]
Hi all

I solved this problem after I updated the version of Pandas from 1.05 to 1.35
